// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ChronoSafe",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ChronoSafe",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.ChronoSafe",
            teamIdentifier: "KMAJ4QDR89",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gift),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly),
                .fileAccess(.pictureFolder, mode: .readOnly),
                .fileAccess(.musicFolder, mode: .readOnly),
                .fileAccess(.moviesFolder, mode: .readOnly),
                .camera(purposeString: "Capture a moment and save it for later"),
                .microphone(purposeString: "Capture a voice note"),
                .photoLibrary(purposeString: "To add photos to time capsule")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)